### ISSUE TITLE
Empty project path

### ISSUE THREAD

**Issue by KYHSGeekCode** [codekidX/osslib-web#4]
The website says
>Empty project path

When I try to add `aquynh/capstone`.

**Comment by codekidX** [comment]
Hello, there is some bug with the Github API when sending us back the repository data. I'll let you know as soon I find out what that is.

Error snippet for reference:

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by codekidX** [comment]
@KYHSGeekCode thanks for reporting, a fix was pushed and deployed.
